import React, { useState } from 'react';
import { Card } from '../components/common/Card';
import { Button } from '../components/common/Button';
import { Badge } from '../components/common/Badge';
import {
  User,
  Shield,
  Lock,
  Bell,
  Download,
  ShieldCheck,
  CheckCircle2,
  Key,
  Database,
  FileSpreadsheet
} from 'lucide-react';
import { Patient } from '../types/clinical';

interface SettingsPageProps {
  patients: Patient[];
}

export const SettingsPage: React.FC<SettingsPageProps> = ({ patients }) => {
  const [activeTab, setActiveTab] = useState<'profile' | 'privacy' | 'security' | 'notifications' | 'export'>('profile');
  const [exportStatus, setExportStatus] = useState<string | null>(null);

  const handleExportData = () => {
    setExportStatus('Generating structured clinical JSON export...');
    setTimeout(() => {
      const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(patients, null, 2));
      const downloadAnchor = document.createElement('a');
      downloadAnchor.setAttribute("href", dataStr);
      downloadAnchor.setAttribute("download", `medlens_clinical_cohort_export_${new Date().toISOString().split('T')[0]}.json`);
      document.body.appendChild(downloadAnchor);
      downloadAnchor.click();
      downloadAnchor.remove();
      setExportStatus('Structured JSON bundle successfully generated and downloaded.');
    }, 600);
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6 animate-fadeIn">
      {/* Header */}
      <div>
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900">Clinical Settings & Security</h2>
        <p className="text-xs sm:text-sm text-slate-500 mt-1">
          Manage practitioner identity, security posture, audit configuration, and data export.
        </p>
      </div>

      {/* Mandatory Privacy Banner */}
      <div className="rounded-xl border border-teal-200 bg-teal-50/80 p-4 text-xs text-teal-950 flex items-start gap-3 shadow-2xs">
        <ShieldCheck className="w-5 h-5 text-teal-700 shrink-0 mt-0.5" />
        <div className="space-y-1">
          <strong className="text-teal-900 font-semibold block text-sm">
            Clinical Privacy & Provenance Architecture
          </strong>
          <p className="text-teal-950/90 leading-relaxed font-normal">
            "MedLens is designed to organize and summarize medical information while keeping source information traceable."
          </p>
          <p className="text-[11px] text-teal-800 pt-1">
            Every token generated by the organizing engine maintains bi-directional audit links to source PDF, JPG, and PNG documents.
          </p>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-slate-200 gap-2 overflow-x-auto text-xs font-semibold">
        {[
          { id: 'profile', label: 'Practitioner Profile', icon: User },
          { id: 'privacy', label: 'Privacy & Traceability', icon: Shield },
          { id: 'security', label: 'Security & Access', icon: Lock },
          { id: 'notifications', label: 'Notifications', icon: Bell },
          { id: 'export', label: 'Data Export', icon: Download },
        ].map((tab) => {
          const Icon = tab.icon;
          const isActive = activeTab === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`flex items-center gap-2 px-4 py-3 border-b-2 font-medium transition-all whitespace-nowrap cursor-pointer ${
                isActive
                  ? 'border-blue-600 text-blue-700 font-bold'
                  : 'border-transparent text-slate-500 hover:text-slate-800'
              }`}
            >
              <Icon className={`w-4 h-4 ${isActive ? 'text-blue-600' : 'text-slate-400'}`} />
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>

      {/* Tab Content */}
      {activeTab === 'profile' && (
        <Card title="Practitioner Profile" subtitle="Your clinical identity and verified institutional credentials">
          <div className="space-y-4 max-w-xl text-xs">
            <div className="flex items-center gap-4 pb-4 border-b border-slate-100">
              <div className="w-16 h-16 rounded-full bg-blue-600 text-white flex items-center justify-center font-bold text-xl shadow-xs">
                SL
              </div>
              <div>
                <h4 className="text-base font-bold text-slate-900">Dr. Sarah Lin, MD</h4>
                <p className="text-slate-500 text-xs">Chief Medical Officer • Internal Medicine</p>
                <div className="flex items-center gap-2 mt-1">
                  <Badge status="verified" label="NPI: 1982049102" />
                  <span className="text-[11px] text-slate-400">License: CA-A149021</span>
                </div>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block font-semibold text-slate-700 mb-1">Email Address</label>
                <input
                  type="email"
                  defaultValue="s.lin@saintjude-health.org"
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg bg-slate-50"
                  readOnly
                />
              </div>

              <div>
                <label className="block font-semibold text-slate-700 mb-1">Department</label>
                <input
                  type="text"
                  defaultValue="Clinical Intelligence & Informatics"
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg bg-slate-50"
                  readOnly
                />
              </div>
            </div>
          </div>
        </Card>
      )}

      {activeTab === 'privacy' && (
        <Card title="Privacy & Data Traceability Protocol" subtitle="Data lineage, non-diagnostic constraints, and source document tracking">
          <div className="space-y-4 text-xs text-slate-700 leading-relaxed max-w-3xl">
            <div className="p-3.5 rounded-lg bg-slate-50 border border-slate-200">
              <h4 className="font-semibold text-slate-900 mb-1">Source Document Lineage</h4>
              <p>
                MedLens never modifies original uploaded files. Every parsed biomarker or condition is stored with cryptographic checksums pointing back to the raw source coordinate bounding box.
              </p>
            </div>

            <div className="p-3.5 rounded-lg bg-slate-50 border border-slate-200">
              <h4 className="font-semibold text-slate-900 mb-1">De-identification & Zero AI Prescriptions</h4>
              <p>
                The organizing engine is strictly restricted by system prompts and post-processors to prohibit diagnostic assertions, treatment instructions, or dosage calculations.
              </p>
            </div>
          </div>
        </Card>
      )}

      {activeTab === 'security' && (
        <Card title="Security & Storage Architecture" subtitle="Current storage implementation, defensive controls, and architectural posture">
          <div className="space-y-3 max-w-2xl text-xs">
            <div className="flex items-center justify-between p-3 rounded-lg border border-blue-200 bg-blue-50/60">
              <div className="flex items-center gap-3">
                <Database className="w-5 h-5 text-blue-700 shrink-0" />
                <div>
                  <span className="font-semibold text-slate-900 block">SQLite Relational Backend (better-sqlite3)</span>
                  <span className="text-slate-600">SQLite backend, not yet encrypted at rest. Tables for patients, reports, tests, and conflicts backed by Express CRUD routes.</span>
                </div>
              </div>
              <Badge status="verified" label="SQLite Active" />
            </div>

            <div className="flex items-center justify-between p-3 rounded-lg border border-slate-200 bg-white">
              <div className="flex items-center gap-3">
                <Shield className="w-5 h-5 text-slate-500 shrink-0" />
                <div>
                  <span className="font-semibold text-slate-900 block">Compliance & Certification Status</span>
                  <span className="text-slate-500">Prototype/MVP environment. No HIPAA or SOC-2 certifications; local browser sandbox for clinical research and testing only.</span>
                </div>
              </div>
              <Badge status="rejected" label="Uncertified / Sandbox" />
            </div>

            <div className="flex items-center justify-between p-3 rounded-lg border border-slate-200 bg-white">
              <div className="flex items-center gap-3">
                <Lock className="w-5 h-5 text-blue-600 shrink-0" />
                <div>
                  <span className="font-semibold text-slate-900 block">Active Transport & Ingestion Controls</span>
                  <span className="text-slate-500">25MB file upload cap, binary magic-byte validation, path traversal neutralization, sliding-window rate limiting, and defensive HTTP security headers.</span>
                </div>
              </div>
              <Badge status="verified" label="Active" />
            </div>
          </div>
        </Card>
      )}

      {activeTab === 'notifications' && (
        <Card title="Notification Preferences" subtitle="Configure automated clinical review alerts">
          <div className="space-y-3 max-w-xl text-xs">
            <label className="flex items-center justify-between p-3 rounded-lg border border-slate-200 hover:bg-slate-50 cursor-pointer">
              <div>
                <span className="font-semibold text-slate-800 block">New Extracted Reports Pending Verification</span>
                <span className="text-slate-500 text-[11px]">Notify immediately when OCR finishes processing a patient file</span>
              </div>
              <input type="checkbox" defaultChecked className="w-4 h-4 text-blue-600 rounded" />
            </label>

            <label className="flex items-center justify-between p-3 rounded-lg border border-slate-200 hover:bg-slate-50 cursor-pointer">
              <div>
                <span className="font-semibold text-slate-800 block">Cross-Record Inconsistency Alerts</span>
                <span className="text-slate-500 text-[11px]">Alert when conflicting allergy or medication records are detected</span>
              </div>
              <input type="checkbox" defaultChecked className="w-4 h-4 text-blue-600 rounded" />
            </label>
          </div>
        </Card>
      )}

      {activeTab === 'export' && (
        <Card title="Clinical Data Export" subtitle="Download structured patient cohort records in standardized formats">
          <div className="space-y-4 max-w-xl text-xs">
            <p className="text-slate-600">
              Export all patient dossiers, extracted laboratory histories, provenance tags, and conflict statuses into structured JSON format for EHR integration.
            </p>

            <div className="flex items-center gap-3">
              <Button
                variant="primary"
                icon={<Download className="w-4 h-4" />}
                onClick={handleExportData}
              >
                Export Cohort Data (JSON)
              </Button>
            </div>

            {exportStatus && (
              <div className="p-3 bg-emerald-50 border border-emerald-200 text-emerald-800 rounded-lg flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                <span>{exportStatus}</span>
              </div>
            )}
          </div>
        </Card>
      )}
    </div>
  );
};
