import React from 'react';
import { ProvenanceType } from '../../types/clinical';
import { FileText, UserCheck, Sparkles } from 'lucide-react';

interface ProvenanceBadgeProps {
  source?: ProvenanceType | 'user_provided' | 'extracted_from_report' | 'ai_generated' | string;
  sourceDocument?: string;
  className?: string;
  size?: 'xs' | 'sm';
}

export const ProvenanceBadge: React.FC<ProvenanceBadgeProps> = ({
  source = 'user_provided',
  sourceDocument,
  className = '',
  size = 'xs'
}) => {
  const sizeClasses = size === 'xs' ? 'px-2 py-0.5 text-[11px]' : 'px-2.5 py-1 text-xs';

  if (source === 'ai_generated') {
    return (
      <span
        title={sourceDocument ? `AI generated: ${sourceDocument}` : "Generated by MedLens clinical organizing pipeline"}
        className={`inline-flex items-center gap-1 rounded-md font-semibold bg-purple-50 text-purple-700 border border-purple-200/80 shadow-2xs ${sizeClasses} ${className}`}
      >
        <Sparkles className="w-3 h-3 text-purple-600 shrink-0" />
        <span>AI generated</span>
      </span>
    );
  }

  if (source === 'extracted_from_report') {
    return (
      <span
        title={sourceDocument ? `Extracted from: ${sourceDocument}` : "Extracted from source laboratory report"}
        className={`inline-flex items-center gap-1 rounded-md font-medium bg-blue-50 text-blue-700 border border-blue-200/80 ${sizeClasses} ${className}`}
      >
        <FileText className="w-3 h-3 text-blue-600 shrink-0" />
        <span>Extracted from report</span>
      </span>
    );
  }

  // Default: user_provided
  return (
    <span
      title="Entered by clinician or clinical intake staff"
      className={`inline-flex items-center gap-1 rounded-md font-medium bg-teal-50 text-teal-800 border border-teal-200/80 ${sizeClasses} ${className}`}
    >
      <UserCheck className="w-3 h-3 text-teal-700 shrink-0" />
      <span>User provided</span>
    </span>
  );
};